Aggiornamento appunti HPC
Typing-Monkeys/AppuntiUniversita pull request #3
Opened 2022-01-22 16:56 UTC by CristianCosci

Sto espandendo gli appunti di HPC integrando le slide.
Volendo posso integrare anche i pdf delle mie relazioni.

2022-01-23 09:43 UTC, ncvescera commented
Ottimo lavoro ! 🐒 
Ti ringrazio davvero tanto, sono sempre felice quando qualcuno apporta modifiche e contribuisce a migliorare questa repo !

Sul contenuto niente da dire, perfetto ! Non approvo molto l'uso di `#` per creare uno spazio, potevi utilizzare `***` o `<hr>` ma sono piccoli dettagli superflui.

Ho notato che  non hai aggiunto nulla su GPGPU, hai del materiale anche per questo ??

2022-01-23 09:59 UTC, CristianCosci commented
Sto procedendo man mano con le slide. Al momento sto integrando la parte su condor, appena termino quello procedo con tutto il resto. 
Correggo l'uso del canceletto per gli spazi.

2022-01-23 15:59 UTC, ncvescera commented
Ok, perfetto !

Sto vedendo man mano le varie modifiche e aggiunte !

Aspetto che finisci tutto e poi effettuo il merge 🚀

2022-01-24 20:06 UTC, CristianCosci commented
Mi manca solo l'ultimo pacco di slide relativo a docker. Poi do una riletta al tutto e correggo eventuali errori di battitura e di layout (Spero di finire domani). 

Ho aggiunto anche alcuni argomenti relativi a delle domande che ha avuto un mio collega al test su libreOL allo scorso appello. Purtroppo se ne ricordava solo poche e nel caso in cui qualcuno abbia già svolto il test e abbia degli argomenti o annotazioni sulle domande avute sarei lieto di aggiungerli agli argomenti degli appunti. 💯

2022-01-25 09:06 UTC, ncvescera commented
Perfetto, ottimo lavoro ! 🚀 

Appena posso inizio a controllare anche io.
Molto bene l'aggiunta delle domande del test, riuscire ad averne un ampio numero non sarebbe male anche perche' usa sempre  le stesse 🌚 .

Se hai svolto le relazioni "mancanti" di HPC (gpgpu e docker) e vorresti condividerle con tutti la cosa e' bene accetta.
Stavo pensando anche di chiedere sul gruppo di wp, magari si ricordano anche altre domande 🤔

2022-01-25 09:30 UTC, CristianCosci commented
Per quanto riguarda le relazioni io ho fatto quelle relative a Condor e HA Cluster ed ho visto che sono già caricate, non è comunque un problema caricarle anche per me. Le altre due purtroppo non le ho fatte. 

Invece per le domande sarebbe molto utile averne altre o perlomeno gli argomenti, in modo da rendere più completi possibile gli appunti. Potremmo chiedere su Whatsapp se qualcuno ha già fatto il test 👍

2022-01-26 14:11 UTC, CristianCosci commented
Ho terminato tutte le slide, procedo ora alla rilettura e correzzione di eventuali errori.
La parte finale su kubernets va  sicuramente migliorata in quanto seguendolo dalle slide ammetto che il contenuto è pessimo e di difficile comprensione soprattuto perchè non segue un filo logico (le slide fanno abbastanza schifo).

2022-01-27 14:28 UTC, TommasoRomani requested changes

2022-01-27 14:28 UTC, TommasoRomani commented on magistrale/Anno 1/HPC/README.md
> +- **StarD**: rappresenta la macchina nel sistema Condor. È responsabile dell'avvio, sospensione e arresto dei job. Un solo demone per ogni nodo.
Sostituire StarD con StartD

2022-01-27 14:40 UTC, CristianCosci commented on magistrale/Anno 1/HPC/README.md
> +- **StarD**: rappresenta la macchina nel sistema Condor. È responsabile dell'avvio, sospensione e arresto dei job. Un solo demone per ogni nodo.
Fatto, scusate per la svista

2022-01-30 08:58 UTC, ncvescera requested changes
C'e' un typo da correggere alla riga 628 🐵

2022-01-30 08:58 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +    - i volumi memorizzano i file sul filesystem dell'host locale per fornire persistenza e sono l'opzione preferita per aggiungere dati persistenti a un container. Sono cartelle che vengono gestite
Typo `possobile` da correggere

```suggestion
    - i volumi memorizzano i file sul filesystem dell'host locale per fornire persistenza e sono l'opzione preferita per aggiungere dati persistenti a un container. Sono cartelle che vengono gestite in automatico da docker dove è possibile salvare file in modo permanente. Generalmente vengono create in `/var/lib/docker/volumes`. Essendo gestite in automatico da Docker, è possibile gestirle con facilità (eliminazione, creazione, ecc).
```

2022-01-30 17:28 UTC, TommasoRomani approved these changes

2022-01-31 13:47 UTC, ncvescera approved these changes

2022-01-31 17:46 UTC, CristianCosci reviewed
Dovrei aver corretto tutti gli errori di battitura

2022-01-31 20:36 UTC, ncvescera requested changes
Trovati alcuni typo:

- riga 26
- riga 28: `caclolo`
- riga 59
- riga 85
- riga 163
- riga 169

2022-01-31 20:36 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +    - Normalmente utilizzato in ambiti scentifici per simulazioni e altro. Questi tipi di cluster aumentano la disponibilità, le prestazioni e la scalabilità delle applicazioni, in particolare attivi
```suggestion
    - Normalmente utilizzato in ambiti scientifici per simulazioni e altro. Questi tipi di cluster aumentano la disponibilità, le prestazioni e la scalabilità delle applicazioni, in particolare attività computazionali o ad alta intensità di dati. Viene utilizzato per eseguire richieste molto costose in code di batch. Viene anche chiamato High Throughput Computing cioè sistemi che permettono di eseguire molte operazioni di calcolo su un lungo periodo di tempo. Un esempio di questo software è HTCondor.
```

2022-01-31 20:36 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
>  A livello di software è imporante gestire il parallelismo che può essere di 3 tipi:
```suggestion
A livello di software è importante gestire il parallelismo che può essere di 3 tipi:
```

2022-01-31 20:36 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +Lo scopo finale di utilizzo di un cluster determina le caratteristiche hardware necessarie (utilizzare computer già di proprietà, assemblare nuovi pc o acqusitare pc preassemblati). Tuttavia i vincol
```suggestion
Lo scopo finale di utilizzo di un cluster determina le caratteristiche hardware necessarie (utilizzare computer già di proprietà, assemblare nuovi pc o acquistare pc preassemblati). Tuttavia i vincoli di budget possono costringere a soluzioni meno ideali. Un consiglio è quello di (se possibile) utilizzare sistemi identici per i nodi, in questo modo sarà sufficiente clonare le varie macchine e la relativa manutenzione e riparazione sarà più semplice.
```

2022-01-31 20:56 UTC, ncvescera requested changes
Trovati typo:

- riga 524
- riga 527
- riga 618
- riga 653
- riga 720
- riga 822
- riga 829

2022-01-31 20:56 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +- **SaaS** (Software as a Servcie): fornisce l'accesso ad applicazioni on demand. Permette di ridurre i costi perchè non è necessario acquistare software completo ma è necessario solo l'acquisto di u
```suggestion
- **SaaS** (Software as a Servcie): fornisce l'accesso ad applicazioni on demand. Permette di ridurre i costi perchè non è necessario acquistare software completo ma è necessario solo l'acquisto di un abbonamento. Un altro aspetto chiave è la Multitenancy che evita all'utente finale tutte quelle operazioni di manutenzione delle macchine.
```

2022-01-31 20:56 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +- **IaaS** (Infrastructur as a Service): è un insieme di macchine virtuali, fisiche, cluster e database. Il tutto è gestito da un Layer superiore che garantisce Runtime Enviroment Customizaion, Appli
```suggestion
- **IaaS** (Infrastructur as a Service): è un insieme di macchine virtuali, fisiche, cluster e database. Il tutto è gestito da un Layer superiore che garantisce Runtime Enviroment Customizaion, Application Isoaltion e QoS. In questo layer ci sono anche gli Hypervisor per la virtualizzazione.
```

2022-01-31 20:56 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +Docker è un progetto open-source che automatizza il processo di deployment di applicazioni all'interno di contenitori software, fornendo un'astrazione aggiuntiva grazie alla virtualizzazione a livell
```suggestion
Docker è un progetto open-source che automatizza il processo di deployment di applicazioni all'interno di contenitori software, fornendo un'astrazione aggiuntiva grazie alla virtualizzazione a livello di sistema operativo. Il deployment e l'isolamento delle applicazioni sono gestite tramite i Container: un pacchetto leggero, standalone ed eseguibile che contiene tutto il necessario per far eseguire un'applicazione.
```

2022-01-31 20:56 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +        - E se avessi un'applicazione che richiede più contenitori e ognuno di essi richiede esattamente gli stessi dati? Sebbene sia possibile creare un volume per ogni contenitore e copiare i dati
```suggestion
        - E se avessi un'applicazione che richiede più contenitori e ognuno di essi richiede esattamente gli stessi dati? Sebbene sia possibile creare un volume per ogni contenitore e copiare i dati in ciascuno, un metodo più efficiente sarebbe condividere un singolo volume tra più contenitori. Una caratteristica unica dei volumi Docker è che più contenitori possono accedere allo stesso volume. Sebbene sembri una soluzione semplice per fornire un'unica posizione ai dati condivisi, è necessario tenere presente che non tutte le applicazioni funzionano bene quando più processi accedono agli stessi dati. Quando si avvia ogni istanza, si usano semplicemente gli stessi nomi per il volume:
```

2022-01-31 20:56 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +Se si avvia un container senza un'opzione di rete, verrà avviato connesso alla rete bridge predefinita. È tuttavia possibile **avviare un container senza una rete** collegata utilizzando il comando *
```suggestion
Se si avvia un container senza un'opzione di rete, verrà avviato connesso alla rete bridge predefinita. È tuttavia possibile **avviare un container senza una rete** collegata utilizzando il comando **--network=none** selezionabile quando si avvia il contenitore. Questo è lo stesso processo che si esegue quando viene avviato un container con una rete definita dall'utente.
```

2022-01-31 20:56 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +- Orchestrazione dello storage permettendo di **montare volumi** o cartelle in modo semlice
```suggestion
- Orchestrazione dello storage permettendo di **montare volumi** o cartelle in modo semplice
```

2022-01-31 20:56 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
>  - Gestione di informazioni sensibili (passowrd, chiavi SSH, OAuth token, ecc.)
```suggestion
- Gestione di informazioni sensibili (password, chiavi SSH, OAuth token, ecc.)
```

2022-02-01 09:49 UTC, TommasoRomani approved these changes

2022-02-01 09:51 UTC, TommasoRomani requested changes
Correggere riga 28

2022-02-01 09:51 UTC, TommasoRomani commented on magistrale/Anno 1/HPC/README.md
>  I principali metodi per migliorare la potenza di caclolo sono:
```suggestion
I principali metodi per migliorare la potenza di calcolo sono:
```

2022-02-01 10:41 UTC, ncvescera approved these changes
Ottimo 👍🏻 !

2022-02-01 11:12 UTC, TommasoRomani approved these changes

2022-02-01 11:15 UTC, ncvescera commented
@CristianCosci Ottimo lavoro 👍🏻

In questi giorni daremo un'ultima ricontrollata a tutti gli appunti e procederemo con il Merge.
Grazie mille del tuo contributo 🦍 !

2022-02-01 11:17 UTC, CristianCosci commented
Perfetto 👍👍

2022-02-01 22:11 UTC, ncvescera requested changes
Trovato typo alla riga 129:  la parola `DRBD` è scritta `DRDB`.

2022-02-01 22:11 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +    Il DRBD (Distributed Replicated Block Device), viene utilizzato per replicare il contenuto informativo all’interno di un nodo master, sui vari nodi slave. Il DRDB esegue la copia live di un disco
```suggestion
    Il DRBD (Distributed Replicated Block Device), viene utilizzato per replicare il contenuto informativo all’interno di un nodo master, sui vari nodi slave. Il DRBD esegue la copia live di un disco tra il server attivo e quello di backup, al fine di garantire la correttezza delle informazioni memorizzate su disco. In combinazione verrà utilizzato Heartbeat, con lo scopo di verificare il corretto funzionamento dei server associati a un determinato servizio. In caso di failover il software esegue lo scambio tra un server di backup e il server primario. Il DRBD è un elemento fondamentale per formare un cluster ad alta disponibilità (HA). Questo viene fatto eseguendo il mirroring di un intero dispositivo tramite una rete assegnata. La funzionalità software di replicazione dei blocchi dell’hard disk del nodo master è completamente trasparente alle applicazioni che ne devono leggere il contenuto. Se ad esempio inseriamo le pagine di un contenuto Web all’interno dello spazio governato dal DRBD, queste verranno replicate su tutti i nodi del cluster garantendo continuità di servizio e consistenza dei dati. Un applicativo software di questo tipo viene installato quando la soluzione che si sta realizzando è fortemente indirizzata all’affidabilità dei dati. Se il nodo primario dovesse incorrere in problematiche di rete, heartbeat, avvierà la procedura che porta uno dei nodi secondari a prendere il posto del primario, garantendo la continuità del servizio offerto. Dopo un’interruzione di un nodo, il DRBD:
```

2022-02-03 10:13 UTC, ncvescera approved these changes

2022-02-07 00:14 UTC, ncvescera requested changes
Trovati alcuni piccoli errori e suggerite alcune modifiche.
Niente di grave o nessun grande cambiamento da apportare.

2022-02-07 00:14 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +- **Amministrazione manuale del nodo**: È possibile creare e modificare gli oggetti Node utilizzando kubectl. Quando si vogliono creare oggetti Node manualmente, va impostato il flag kubelet --node-r
Mettere in evidenza i comandi per la configurazione.

```suggestion
- **Amministrazione manuale del nodo**: È possibile creare e modificare gli oggetti Node utilizzando kubectl. Quando si vogliono creare oggetti Node manualmente, va impostato il flag kubelet `--node-registert=false`. È possibile modificare gli oggetti Node indipendentemente dall'impostazione di `--register-node`. Ad esempio, si possono impostare etichette su un nodo esistente o contrassegnarlo come non programmabile. È possibile utilizzare le etichette sui nodi insieme ai selettori di nodi sui pod per controllare la pianificazione. Oppure puoi vincolare un Pod in modo che sia idoneo all'esecuzione solo su un sottoinsieme dei nodi disponibili. Invece contrassegnare un nodo come non pianificabile impedisce allo scheduler di posizionare nuovi pod su quel nodo ma non influisce sui pod esistenti sul nodo. Ciò è utile come passaggio preparatorio prima del riavvio di un nodo o di altre operazioni di manutenzione.
```

2022-02-07 00:14 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +    - **Oggetto stato**: Lo stato descrive il corrente stato dell'oggetto, fornito e aggiornato dal sistema Kubernetes e dai suoi componenti. Il piano di controllo di Kubernetes gestisce continuament
C'era un problema con questa frase.

```suggestion
    - **Oggetto stato**: Lo stato descrive il corrente stato dell'oggetto, fornito e aggiornato dal sistema Kubernetes e dai suoi componenti. Il piano di controllo di Kubernetes gestisce continuamente e attivamente l'effettivo stato di ogni oggetto per abbinare lo stato fornito.
```

2022-02-07 00:14 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
> +    Quando crei un oggetto in Kubernetes, devi fornire l'oggetto spec che descrive lo stato desiderato, nonché alcune informazioni di base sull'oggetto (come un nome). Quando utilizzi l'API Kubernete
La frase che inizia da `Molto spesso, ...` risulta non essere molto chiara.
Ricontrollala pls ⏪

2022-02-07 00:14 UTC, ncvescera commented on magistrale/Anno 1/HPC/README.md
>      - [Load Balacing](#load-balacing)
Il collegamento non funziona

2022-02-08 15:09 UTC, merged