feat(algoritmi avanzati) aggiunti appunti pinotti
Typing-Monkeys/AppuntiUniversita pull request #37
Opened 2023-04-12 14:19 UTC by FabioBocchini

Ho scritto gli appunti per l'esame della pinotti, sono principalmente le cose scritte sulle slide ed un po' di cose scritte a lezione. Non sono un granché ma dovrebbero essere utili

2023-04-12 19:18 UTC, CristianCosci commented
Gli argomenti trattati a lezione sono tutti presenti o ci sono altri argomenti da aggiungere?

2023-04-13 07:42 UTC, FabioBocchini commented
> Top!
> Gli argomenti trattati a lezione sono tutti presenti o ce ne sono altri da aggiungere?

Sono tutti

2023-04-13 12:45 UTC, ncvescera requested changes
La maggior parte delle formule 'centrate' (quelle con i doppi `$`) non vengono renderizzate bene. Anche alcune formule inline hanno questo problema.
Te ne ho segnalate alcune, ma ce ne sono anche altre !

Se puoi ricontrollale e correggile, sennò ci pensiamo noi quando inizieremo a studiare questo esame

2023-04-13 12:45 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/Readme.md
> +$$
Questa formula non viene renderizzata bene

2023-04-13 12:45 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/Readme.md
> +$$
Questa formula non viene renderizzata bene.

2023-04-13 12:45 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/Readme.md
> +- per ogni problema ho n scelte ( $O(n^2)$) ma per computare $e(i,j)$$ **TEMPO =** $O(n^3)$
Ci sono alcune formule che non vengono renderizzate bene.

2023-04-13 12:45 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/Readme.md
> +$$
Questa formula non viene renderizzata bene.

2023-04-14 07:54 UTC, ncvescera submitted a review, later dismissed
Ottimo 👍🏻 
Ad una prima (e veloce) lettura tutte le formule vengono mostrate bene 🚀

2023-04-15 14:25 UTC, CristianCosci commented
Ho iniziato a ricontrollare gli appunti e ad integrare/aggiungere materiale

2023-05-09 09:19 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +Costruisco una matrice dove salvo i risultati dei sottoproblemi. Quando devo accedere ad un sottoproblema, prima di ricalcolarlo, controllo se è presente nella matrice.
Si è un array

2023-05-11 07:34 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +			M[j, W] ← max { M [j – 1, W], vj + M [j – 1, W – wj] }
come mai in questa riga utilizzi `vj` ?
Non dovrebbe essere `wj`?

Qui prendiamo in considerazione una versione un po diversa del Knapsack Problem, quello dove massimizziamo solo la somma dei pesi e il 'valore' dell'oggetto non esiste.
Se non sbaglio questa è l'implementazione del Knapsack Problem tenendo conto del valore degli oggetti

2023-05-16 08:43 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +- `Nel caso 2`, si paga un gap cost $\delta$ dato che la $m^{th}$ posizione di $X$ non è in matching, e poi si allinea $x_1 x_2 \ldots x_{m-1}$ nel miglior modo possibile con $y_1 y_2 \ldots y_{n}$.
@CristianCosci è la `m` che viene decrementata, non la `n` giusto ?

```suggestion
- `Nel caso 2`, si paga un gap cost $\delta$ dato che la $m^{th}$ posizione di $X$ non è in matching, e poi si allinea $x_1 x_2 \ldots x_{m-1}$ nel miglior modo possibile con $y_1 y_2 \ldots y_{n}$. Si ha quindi che $OPT(m,n) = \delta + OPT(m-1,n)$.
```

2023-05-16 10:03 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +$$
É del libro, lei le usa nei suoi appunti

2023-05-16 14:15 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +$$
@CristianCosci le sommatorie vanno sommate e non moltiplicate (?)

```suggestion
$$
avgCost(T) = 1 + \sum_{i=1}^{n} \text{profondità}_T (k_i) \cdot p_i + \sum_{i = 0}^{n} \text{profondità}_T (d_i) \cdot q_i
$$
```

2023-05-16 14:45 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +​	  $f((0,0)(n/2,q)) + f((n/2,q)(n,m))$
@CristianCosci hai invertito gli indici ?

```suggestion
​	  $f((0,0)(q,n/2)) + f((q,n/2)(m,n))$ 
```

2023-05-16 15:55 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +$$
manca il +, non sono moltiplicate

2023-05-16 16:10 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +
Non l'ho scritta io quella parte, era già presente, se non combacia con gli indici di prima correggetelo

2023-05-16 16:36 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +
Risolto in febe664

2023-05-16 16:44 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +- C'è un parametro $\delta>0$ che definisce la **gap penalty** , ovvero ogni volta che bisogna aggiungere un simbolo (-) per far si che le due parole siano
Mi pare molto alla carlona dire "quando si aggiunge il simbolo -"

2023-05-16 16:44 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +<img src="./imgs/sa.png" width="50%"/> <img src="./imgs/seqalignmatrix.png" width="40%"/>
manca la foto

2023-05-16 16:44 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +- C'è un parametro $\delta>0$ che definisce la **gap penalty** , ovvero ogni volta che bisogna aggiungere un simbolo (-) per far si che le due parole siano
Se proprio volete essere esplicativi lo aggiungerei tra parentesi e non come spiegazione

2023-05-16 17:19 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +- C'è un parametro $\delta>0$ che definisce la **gap penalty** , ovvero ogni volta che bisogna aggiungere un simbolo (-) per far si che le due parole siano
è effettivamente quello che succede però. Se c'è un gap vai ad aggiungere uno spazio (appunto un gap) che è identificato dal 'trattino' (-) per far allineare le due stringhe.

Abbiamo riletto il libro ed è proprio quello che dice

2023-05-16 17:19 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +- C'è un parametro $\delta>0$ che definisce la **gap penalty** , ovvero ogni volta che bisogna aggiungere un simbolo (-) per far si che le due parole siano
@TommasoRomani cita il libro quando definisce la gap penalty

2023-05-16 17:31 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> -abbiamo **3 gap** ma **nessun mismatch**.
Non penso mandare a capo le righe così sia una buona idea, magari su VSCode ti evita di vedere la preview con dei ritorni a capo, ma su GitHub non si sono. Scrivere 800 e passa caratteri in una sola riga risulta estremamente difficile da leggere e modificare quando serve.

2023-05-16 17:34 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +<img src="./imgs/sa.png" width="50%"/> <img src="./imgs/seqalignmatrix.png" width="40%"/>
Caricata foto in 7fe494b

2023-05-16 17:58 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
> +mean-
l'esempio si riferisce all'immagine caricata? Se si, non è errato? Se no, non è meglio inserire quello dell'immagine?

2023-05-27 13:07 UTC, NicoloPosta submitted a review, later dismissed

2023-06-05 15:18 UTC, F-a-b-r-i-z-i-o commented
@ncvescera 
Io e @FabioBocchini  ci siamo accorti, che mancano alcuni argomenti che la prof ha fatto a lezione durante il nostro anno e sono i seguenti:

- Shortest path maximum flow
- Fat flow algorithm
- Preflow push

Abbiamo inserito un po' di materiale (da ricontrollare) che abbiamo trovato negli appunti scritti a mano durante le lezioni.

2023-06-05 15:25 UTC, ncvescera commented
@FabioBocchini @F-a-b-r-i-z-i-o ho visto lo Shortest Path Maximum Flow, ma gli altri due non li avete aggiunti ancora ?

2023-06-05 15:27 UTC, F-a-b-r-i-z-i-o commented
@ncvescera calma dio :cactus:

2023-06-05 16:46 UTC, F-a-b-r-i-z-i-o commented
@ncvescera dovrebbe essere tutto :singer:  :microphone: :woman_singer:

2023-06-05 16:58 UTC, ncvescera commented
@F-a-b-r-i-z-i-o tu ci menti 🌚 dici di aver messo cose e compaiono dopo vari commit.

Ora ti tengo d'occhio 🔍

2023-06-05 17:01 UTC, F-a-b-r-i-z-i-o commented
@ncvescera 🦑🦑🦑🦐🐫🐬🐃

2023-06-05 17:05 UTC, F-a-b-r-i-z-i-o commented
@ncvescera 👨🏿‍💼❤️🛎️

2023-07-09 14:23 UTC, CristianCosci approved these changes

2023-07-09 14:37 UTC, ncvescera commented
@CristianCosci, @NicoloPosta @TommasoRomani hanno riscritto questi appunti in latex con alcuni miglioramenti, ma non hanno ancora effettuato il commit. Aspettiamo che carichino le modifiche qui o mergiamo e poi apriremo una nuova PR ?

2023-07-11 17:02 UTC, ncvescera approved these changes

2023-07-11 17:04 UTC, merged