Ho espanso e approfondito gli appunti di Milani per il corso di AI. Ovviamente è necessaria una rilettura per eventuali errori sia grafici che ortografici. Nei prossimi giorni provvederò.
Typing-Monkeys/AppuntiUniversita pull request #4
Opened 2022-02-14 11:13 UTC by CristianCosci

2022-02-14 14:12 UTC, ncvescera commented
Perfetto ! 🚀 
Appena possibile provvederemo anche noi a ricontrollare tutto.

Apprezziamo molto il tuo contributo 🦧

2022-02-16 14:18 UTC, ncvescera commented on magistrale/Anno 1/Milani/README.md
> +### **Tipi di agente**:
Ottimo che hai modificato questa parte descrivendo meglio cosa sono e fanno i tipi di agente 🚀

2022-02-16 14:49 UTC, ncvescera commented on magistrale/Anno 1/Milani/README.md
> +Utilizza quindi una cosa LIFO per ordinare la coda che contine i nodi di frontiera.
Typo: 

```suggestion
Utilizza quindi una coda LIFO per ordinare la coda che contine i nodi di frontiera.
```

2022-02-16 15:16 UTC, ncvescera requested changes
Ho trovato alcuni typo da correggere

2022-02-16 15:16 UTC, ncvescera commented on magistrale/Anno 1/Milani/README.md
> +_Esempio di funzionamento della IDS <br>
```suggestion
_Esempio di funzionamento della IDS:_ <br>
```

2022-02-16 15:16 UTC, ncvescera commented on magistrale/Anno 1/Milani/README.md
> +E' un algoritmo di ricerca che espande parallelamente nodi partendo sia dallo Start che dal Goal fin quando non si incontrano in un punto "centrale". Può essere implementato utilizzando vari algoritm
```suggestion
E' un algoritmo di ricerca che espande parallelamente nodi partendo sia dallo Start che dal Goal fin quando non si incontrano in un punto "centrale". Può essere implementato utilizzando vari algoritmi di ricerca, quello che fornisce prestazioni migliori è la BFS. <br>
```

2022-02-16 15:16 UTC, ncvescera commented on magistrale/Anno 1/Milani/README.md
> +Ha una complessità in tempo e spazio di `O(b ^(d/2))` <br>
Se riesci ad aggiungere la formula matematica scritta meglio non sarebbe male.
Senno' lascialo pure cosi' che si capisce lo stesso 👍🏻

2022-02-16 15:16 UTC, ncvescera commented on magistrale/Anno 1/Milani/README.md
> +_Esempio di funzionamento di A* <br>
```suggestion
_Esempio di funzionamento di A*:_ <br>
```

2022-02-17 08:17 UTC, CristianCosci commented on magistrale/Anno 1/Milani/README.md
> +Ha una complessità in tempo e spazio di `O(b ^(d/2))` <br>
Ho provato ad aggiungerla scrivendola in maniera corretta con i vari tag, ma non so perchè nella visualizzazione su github non viene renderizzata correttamente

2022-02-17 08:48 UTC, ncvescera commented on magistrale/Anno 1/Milani/README.md
> +Ha una complessità in tempo e spazio di `O(b ^(d/2))` <br>
Github non mostra le formule matematiche scritte tra `$$`, è per questo che abbiamo utilizzato tutte quelle gif !
Puoi anche lasciarla così, non è un problema.

In caso puoi usare questo per evitare di scaricare le varie immagini:

```markdown
[formula a ](https://render.githubusercontent.com/render/math?math=e^{i%20\pi}%20=%20-1)
```
Oppure:
```markdown
<img src="https://render.githubusercontent.com/render/math?math=e^{i \pi} = -1">
```

Noi le abbiamo scaricate per essere più sicuri, se quel server cade o lo chiudono, non vedremo più quell'immagine 😢

2022-02-17 08:49 UTC, ncvescera approved these changes
Ottimo !

2022-02-17 09:13 UTC, CristianCosci commented on magistrale/Anno 1/Milani/README.md
> +Ha una complessità in tempo e spazio di `O(b ^(d/2))` <br>
Perfetto grazie mille

2022-02-17 09:43 UTC, ncvescera commented on magistrale/Anno 1/Milani/README.md
> +Ha una complessità in tempo e spazio di `O(b ^(d/2))` <br>
Di nulla 🦧

2022-03-21 14:26 UTC, merged