Caricati appunti Navarra
Typing-Monkeys/AppuntiUniversita pull request #41
Opened 2023-07-04 10:20 UTC by CristianCosci

Appunti Navarra prima bozza

TODO LIST:
- [ ] Aggiungere Docker
- [ ] Cambiare Template
- [ ] Correggere eventuali typo
- [ ] Rimuovere foto inutili dalle rispettive cartelle

2023-07-04 11:22 UTC, ncvescera commented
Ottimo 👍🏻

2023-07-04 22:35 UTC, F-a-b-r-i-z-i-o commented
Alcune possibili domande reperite: 

- Broadcast.
    - Costo.
    - Perché è corretto.
    - Dimostrazione del perché il lower bound è m.

- Protocollo two-bits.
    - Dimostrazione del fatto che in un albero ci siano 2 centri
  
- Articolo scientifico, caso ottimizzato

2023-07-06 11:03 UTC, ncvescera approved these changes
Ci sono alcuni TODO da ricontrollare (@CristianCosci  @ncvescera )

2023-07-06 11:03 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +\end{definition}
È corretto ??

2023-07-06 11:03 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +finale alla fine vale e non cambia.
In questa parte ci sono troppi "dove".
È corretto così ?

2023-07-06 11:03 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/sistemi-sincroni/main.tex
> +\TODO[inline]{Ricontrollare stile Limitazioni}
@ncvescera ricontrollare

2023-07-06 11:03 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/sistemi-sincroni/main.tex
> +
È corretto dove ho fatto terminare la dimostrazione o prende anche il pezzo "Numbero di bit" sotto ?

2023-07-06 11:17 UTC, ncvescera requested changes

2023-07-06 11:17 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/broadcast/main.tex
> +\end{lstlisting}
Avevo acluni dubbi su questo codice perchè l'ho dovuto riscrivere per un mio problema.
È corretto ??

2023-07-06 11:17 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/gathering/main.tex
> +\emph{R. Kalsing, E. Markou, A. Pelc - Gathering Asynchronous Oblivious Mobile Robots In A Ring} \TODO[]{cos'e questo ?}
È la citazione al paper da dove l'hai preso ?

2023-07-06 11:17 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +\end{definition}
È corretto ??

2023-07-06 11:17 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +finale alla fine vale e non cambia.
In questa parte ci sono troppi "dove".
È corretto così ?

2023-07-06 11:17 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/sistemi-sincroni/main.tex
> +\TODO[inline]{Ricontrollare stile Limitazioni}
@ncvescera ricontrollare

2023-07-06 11:17 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/sistemi-sincroni/main.tex
> +
È corretto dove ho fatto terminare la dimostrazione o prende anche il pezzo "Numbero di bit" sotto ?

2023-07-06 13:51 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/gathering/main.tex
> +\emph{R. Kalsing, E. Markou, A. Pelc - Gathering Asynchronous Oblivious Mobile Robots In A Ring} \TODO[]{cos'e questo ?}
Intendi da dove ho preso il paper?

2023-07-06 13:51 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +\end{definition}
A mio parere si, però se hai un dubbio dimmi

2023-07-06 13:55 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/gathering/main.tex
> +\emph{R. Kalsing, E. Markou, A. Pelc - Gathering Asynchronous Oblivious Mobile Robots In A Ring} \TODO[]{cos'e questo ?}
Intendo cosa rappresenta quella riga.
È una citazione al papaer che hai usato per fare gli appunti ?

2023-07-06 14:15 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +\end{definition}
No, hai preso tutto. È corretto

2023-07-06 14:16 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/broadcast/main.tex
> +\end{lstlisting}
È corretto

2023-07-06 14:32 UTC, ncvescera requested changes

2023-07-06 14:32 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/gathering/main.tex
> +          tutti. Ovvero che nessun robot si può speacchiare con un altro robot
La parola corretta è specchiare ?
```suggestion
          tutti. Ovvero che nessun robot si può specchiare con un altro robot
```

2023-07-06 14:32 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/leader-election/main.tex
> +messaggi nei link rimastigli, uno rimarrà quindi nel bordo e proseguirà nel
Secondo VSCode `rimastigli` è un typo. Si scrive `rimastegli` ?

```suggestion
messaggi nei link rimastegli, uno rimarrà quindi nel bordo e proseguirà nel
```

2023-07-06 14:32 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/leader-election/main.tex
> +\colorbox{yellow}{\textbf{Quanti candidati possono essere presenti allo stage
Il testo sottolineato di giallo lo lasciamo così o lo rendiamo normale ?

2023-07-06 14:33 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/gathering/main.tex
> +          tutti. Ovvero che nessun robot si può speacchiare con un altro robot
Si, giusto

2023-07-06 14:34 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/leader-election/main.tex
> +messaggi nei link rimastigli, uno rimarrà quindi nel bordo e proseguirà nel
Metterei "che gli sono rimasti" per evitare ogni dubbio

2023-07-06 14:35 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/leader-election/main.tex
> +\colorbox{yellow}{\textbf{Quanti candidati possono essere presenti allo stage
Possiamo metterlo in grassetto e corsivo insieme togliendo il sottolineato

2023-07-06 14:45 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/leader-election/main.tex
> +\colorbox{yellow}{\textbf{Quanti candidati possono essere presenti allo stage
Ok perfetto !
Possiamo scriverlo da qualche parte 🤔 
in un possibile readme dove magari mettiamo tutto il programma di navarra o una roba simile.
Poi vediamo 🦧

2023-07-06 14:50 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/sistemi-sincroni/main.tex
> +\TODO[inline]{Ricontrollare stile Limitazioni}
Risolto in 7dcbc5e

2023-07-06 14:53 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/leader-election/main.tex
> +messaggi nei link rimastigli, uno rimarrà quindi nel bordo e proseguirà nel
Risolto in 159d2a1

2023-07-06 15:00 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/leader-election/main.tex
> +\colorbox{yellow}{\textbf{Quanti candidati possono essere presenti allo stage
Ho provato ad effettuare la modifica e non mi piace. Perde molto. Non riesci immediatamente a capirne l'importanza 🤔 
Potremmo pensare di creare uno stile apposta, tipo un mini riquadrino attorno al testo o una roba simile

2023-07-10 14:19 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +    distribuito}. È costituito da un insieme finito $\epsilon$ di \textbf{entità}
L'insieme delle entità qui viene chiamato $\epsilon$ e poi nella sezione dopo $\xi$.
È un errore o sono due cose diverse ?

2023-07-10 14:21 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +diciamo che la regola è abilitata da $(s, e)$.\\
>diciamo che la regola è abilitata da $(s, e)$.\\

È la regola che è abilitata o l'azione ?

2023-07-10 14:32 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +omogeneo.\\
Questa può essere resa come un teorema

2023-07-10 14:50 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +    finirà per arrivare nella sua integrità ed essere elaborato.
Togliere dall'assioma

(così come per gli altri sotto)

2023-07-10 14:56 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +    V }$ è l'insieme di queste etichette iniettive.
```suggestion
    etichettati} $(\overrightarrow{G}, \lambda)$, dove $\lambda = \{\lambda_x : x \in
    V \}$ è l'insieme di queste etichette iniettive.
```

2023-07-10 15:46 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +              \item \textbf{Entity workload}: $L_{NODE} = M / |V|$, media di
potrebbe essere meglio scriverla come frazione ?

$\frac{M}{|V|}$

2023-07-10 15:48 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +          della catena più lunga di trasmissioni casuali di messaggi affidabilit, fra
```suggestion
          della catena più lunga di trasmissioni casuali di messaggi affidabili, fra
```

2023-07-10 15:50 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +Sia $\sum(0) = {\sigma (x, 0) : x \in \xi}$ l'insieme di tutti gli stati interni
```suggestion
Sia $\sum(0) = \{\sigma (x, 0) : x \in \xi\}$ l'insieme di tutti gli stati interni
```

2023-07-11 16:19 UTC, ncvescera requested changes

2023-07-13 14:32 UTC, ncvescera requested changes

2023-07-23 16:11 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/broadcast/main.tex
> +\section{Protocollo Flooding: Miglioramento del Broadcasts}
@CristianCosci la togliamo quella 's' finale ?
```suggestion
\section{Protocollo Flooding: Miglioramento del Broadcast}
```

2023-07-23 17:00 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +    \item Denotiamo con $N_{out}(x) \subset \xi$ l'insieme delle entità a cui $x$
No, perchè un entità non può essere vicina di se stessa

2023-07-24 15:55 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/broadcast/main.tex
> +\section{Protocollo Flooding: Miglioramento del Broadcasts}
si, direi di si

2023-07-25 20:34 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/saturazione/main.tex
> +Si assume sempre rete ad Albero.
Viene ripetuto anche nella riga precedente, lo toglierei.

```suggestion
```

2023-07-28 15:49 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/costruzione-spanning-tree/main.tex
> +              sarà sicuramente connesso
Questo è un secondo modo per dimostrare la cosa o il continuo della dimostrazione?

2023-07-28 17:01 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/costruzione-spanning-tree/main.tex
> +              sarà sicuramente connesso
è tipo una riformulazione del concetto con le specifiche parole di neybar

2023-07-28 19:10 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/costruzione-spanning-tree/main.tex
> +              sarà sicuramente connesso
Quindi posso renderlo come abbiamo fatto anche in un altra parte "metodo 1" e "metodo 2" ?

2023-07-29 08:16 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/costruzione-spanning-tree/main.tex
> +              sarà sicuramente connesso
Io scriverei: "In altre parole:..."
In quanto non sono differenti come spiegazioni, è solo riformulata

2023-07-29 08:18 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/costruzione-spanning-tree/main.tex
> +              sarà sicuramente connesso
Perfetto 🚀 
Sto sistemando gli appunti, appena ho fatto faccio il push (metto tutto in un unico commit)

2023-07-29 09:46 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/costruzione-spanning-tree/main.tex
> +              sarà sicuramente connesso
Sistemato in f3ff10e

2023-07-29 09:48 UTC, ncvescera commented
Con il commit f3ff10e ho corretto la maggior parte delle formule, le volte in cui perti del testo necessitavano di essere in formula matematica ed alcune imprecisini.

Rimangono ancora un TODO da rivedere e sistemare le "virgolette".
Dobbiamo anche ricontrollare un po' l'impaginazione che in alcuni casi potrebbe essere migliorata.

@CristianCosci Avevamo trovato alcune formule o costi errati che non avevamo corretto ?

2023-07-29 09:50 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/leader-election/main.tex
> +\colorbox{yellow}{\textbf{Quanti candidati possono essere presenti allo stage
@CristianCosci direi di rimuovere le parti in giallo dato che sono totalmente inutili (abbiamo visto non chiedere quello all'esame 🙃 )

2023-07-29 09:51 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/introduzione_ambiente-distribuito/main.tex
> +              \item \textbf{Entity workload}: $L_{NODE} = M / |V|$, media di
va bene così com'è

2023-07-29 09:53 UTC, CristianCosci commented
> Con il commit [f3ff10e](https://github.com/Typing-Monkeys/AppuntiUniversita/commit/f3ff10ecf833a6ee5cbf18f2955fac51645180a1) ho corretto la maggior parte delle formule, le volte in cui perti del testo necessitavano di essere in formula matematica ed alcune imprecisini.
> 
> Rimangono ancora un TODO da rivedere e sistemare le "virgolette". Dobbiamo anche ricontrollare un po' l'impaginazione che in alcuni casi potrebbe essere migliorata.
> 
> @CristianCosci Avevamo trovato alcune formule o costi errati che non avevamo corretto ?

No, le uniche formule su cui aveva dei dubbi e che non abbiamo corretto erano evidenziate con un TODO

2023-07-29 10:17 UTC, F-a-b-r-i-z-i-o commented
@CristianCosci @ncvescera 

Potreste, perfavore (vi prego molto), caricare le domande fatte?

2023-07-30 15:05 UTC, ncvescera commented
> Potreste, perfavore (vi prego molto), caricare le domande fatte?

Sono letteralmente sempre le stesse.
Ti chiede:

- Cosa sai dirmi del Broadcast/Wake-Up
- Sai dimostrarmi perchè il lower bound del problema (Broadcast/Wake-Up che tanto è la stessa dimostrazione) è proprio $m$
- Cosa sai dirmi dell'algoritmo Speed/TwoBits
- Sai dimostrarmi perchè in un albero ci sono 2 centri 

@CristianCosci potremmo creare un README dove andiamo ad indicare il programma del Corso, gli argomenti che sono presenti negli appunti e una sezione domande dove scriviamo le domande e consigli su come rispondere 🤔

2023-08-12 16:44 UTC, ncvescera requested changes
Eliminare cartella `old/`

2023-08-13 12:10 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/.devcontainer/Dockerfile
> +
Quelle dipendenze sono all'interno del file `requirements.txt`. Quando compili il devcontainer dovrebbe in automatico installarle una volta avviato. 

Hai provato e non funziona ?

2023-08-13 12:10 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/.devcontainer/Dockerfile
> +
> 🇦🇮

🇺🇬

2023-08-13 18:28 UTC, F-a-b-r-i-z-i-o commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/.devcontainer/Dockerfile
> +
yes, funziona, thanks :1st_place_medal: 
@ncvescera

2023-08-13 20:29 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/.devcontainer/Dockerfile
> +
> yes, funziona, thanks 🥇 @ncvescera

Perfetto 🏵

2023-08-16 14:18 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/main.tex
> +
> Se non viene modificato altro in qualche modo strano, direi perfetto

ad una prima e veloce occhiata sembra di no, ricontrollo meglio ed in caso effettuo il commit 🚀

2023-08-16 17:00 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/main.tex
> +
Ricontrollando bene, l'impaginazione viene alterata.
Non saprei come valutarla (migliore, peggiore, ecc).
Sicuramente, introducendo questa nuova modifica l'imaginazione va tutta ricontrollate.

Ti allego il PDF con le nuove modifiche e quello attuale.

[PDF Attuale](https://github.com/Typing-Monkeys/AppuntiUniversita/files/12361774/Appunti_Navarra.pdf)
[PDF con Modifiche Proposte](https://github.com/Typing-Monkeys/AppuntiUniversita/files/12361775/main.pdf)

2023-08-16 18:54 UTC, F-a-b-r-i-z-i-o submitted a review, later dismissed

2023-08-17 06:48 UTC, ncvescera requested changes

2023-08-17 06:48 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/leader-election/main.tex
> +\TODO[inline]{ricontrollare. Il primo dovrebbe essere n+k-2}
Abbiamo un TODO da risolvere.

Le formule seguenti erano corrette se non sbaglio 🤔 @CristianCosci

2023-08-17 15:54 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/capitoli/leader-election/main.tex
> +\TODO[inline]{ricontrollare. Il primo dovrebbe essere n+k-2}
Si erano corrette

2023-08-17 15:56 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/main.tex
> +
Perfetto, domani me lo guardo bene e ti dico

2023-08-17 15:57 UTC, CristianCosci commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/main.tex
> +
Altrimenti si può sicuramente trovare un modo per rendere più carina la pagina iniziale senza intaccare il resto

2023-08-17 16:10 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/main.tex
> +
Da quello che ho capito il pacchetto `geometry` dà la possibilità di modificare i parametri del foglio come i margini, l'area di testo utilizzabile, ecc.
Usare questo pacchetto senza specificare nulla dovrebbe andare a modificare i settaggi del foglio rendendolo leggermente più largo e stretto (in sostanza aumenta la width e diminuisce la height del foglio).
Quando lo guarderai ti renderai conto che il testo sembra leggermente più "schiaccaito".

Ora la domanda è: Vogliamo impostare noi dei valori custom (che poi saranno gli stessi per tutti gli appunti), usare quelli di default di geometry (e quindi includerlo in tutti gli appunti) o usare le impostazioni di default di LaTex ?

Dovrebbe esserci la possibilità di modificare i volori del foglio di una sola pagina volendo.

2023-10-07 10:12 UTC, ncvescera commented on magistrale/Anno 1/Advanced and Distributed Algorithms/Navarra/latex/main.tex
> +
@CristianCosci direi che lasciamo tutto così com'è. Alla fine l'impaginazione attuale va più che bene.

2023-10-07 10:13 UTC, ncvescera approved these changes

2023-10-10 08:57 UTC, F-a-b-r-i-z-i-o approved these changes

2023-10-10 09:01 UTC, merged