Correzione e aggiunta appunti Santini
Typing-Monkeys/AppuntiUniversita pull request #43
Opened 2023-07-05 22:50 UTC by Meht-evaS

Aggiunta lingua italiana per correggere sillabazione ritorno a capo

Corretti alcuni esempi (sia di buffer overflow che SQL INJECTION)

Aggiornata piccola parte sulla PoS di Etheruem

Corretti errori grammaticali o lessicali

Sostituiti i simboli delle doppie virgolette con gli apici aperti e chiusi

Aggiunto capitolo WebSecurity - Santini

2023-07-06 21:01 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/xxe.tex
> +Come possiamo vedere, questo codice presenta più di un problema ma il più importante sicuramente è che potremmo chiamare noi stessi la funzione sendScreenshotToSupport() con le nostre immagini. Potre
```suggestion
Come possiamo vedere, questo codice presenta più di un problema ma il più importante sicuramente è che potremmo chiamare noi stessi la funzione \verb|sendScreenshotToSupport()| con le nostre immagini. Potremmo quindi falsificare la richiesta di rete e inviare al server il nostro payload personalizzato in cui cerchiamo di ottenere il file ``\verb|/etc/passwd|'':
```

2023-07-06 21:04 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/xxe.tex
> +N.B. Per un hacker è facile capire se un'azienda usa XML o meno e la maggior parte delle volte lo usa. Questo perchè quando le aziende di software aziendale crescono, spesso aggiornano il loro softwa
```suggestion
\textbf{Nota:} Per un hacker è facile capire se un'azienda usa XML o meno e la maggior parte delle volte lo usa. Questo perchè quando le aziende di software aziendale crescono, spesso aggiornano il loro software in modo frammentario piuttosto che costruirlo tutto da zero. Ciò significa che spesso le moderne API JSON/REST si interfacciano in un punto o nell'altro con un'API XML/SOAP.
```
Una roba del genere, o se preferisci, lascia N.B. ma mettilo in grassetto

2023-07-06 21:05 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/fonts/NotoColorEmoji.ttf
Questo file va rimosso

2023-07-06 21:15 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/dos.tex
Ottimo 👍🏻

2023-07-06 21:16 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/main.tex
> +\setemojifont{NotoColorEmoji.ttf}[Path=fonts/]
Questa parte va rimessa com'era una volta effettuate tutte le modifiche

2023-07-06 21:32 UTC, ncvescera commented
@CristianCosci @F-a-b-r-i-z-i-o @NicoloPosta @TommasoRomani Siamo di fronte ad un dilemma, @Meht-evaS ha apportato delle modifiche agli appunti di Santini e Bistarelli (Cybersecurity) ed ha aggiunto dei `\vspace` nel codice LaTex per andare ad aggiungere o togliere spazio tra i titoli ed il testo nornale (non solo, ma molto spesso).

Possiamo qui vederne alcuni effetti

![image](https://github.com/Typing-Monkeys/AppuntiUniversita/assets/10250769/59c2c4ef-d0b5-4aa4-b3eb-cdc2d5d0f5e4)
-------
![image](https://github.com/Typing-Monkeys/AppuntiUniversita/assets/10250769/b00ed780-cb03-48fa-a2cc-92bb85b0cbde)
-------
![image](https://github.com/Typing-Monkeys/AppuntiUniversita/assets/10250769/6f9b82a3-935c-43b4-a7e9-9637710a23ee)
---------

Io personalmente non penso vadano utilizzati dato che vanno a sbilanciare molto l'equilibrio che c'è nel PDF. Le distanze che LaTex imposta di default penso non vadano cambiate o meglio, vanno impostate all'inizio in modo da avere una continuità e coerenza in tutto il documento. 
Preferisco che alcuni parti del testo vadano a pagina nuova invece che metterle tutte nella stessa pagina andando  a modificare le varie distanze.

Voi cosa ne pensate ? Li teniamo o li togliamo ?

2023-07-07 08:47 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +\paragraph{Esempio.}\
Si si, ne basta uno. Se lo elimino il testo diventa tutto su una riga.

2023-07-07 08:49 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +Alla fine la variabile \verb|x| conterrà il valore $100+256=356$. \\
Erano solo sbagliati i numeri. Con quelli di prima l'esempio non ritornava.

2023-07-07 09:01 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo9_xss.tex
> +slot definiti dalla Rule \#0 alla Rule \#4.
Si vede che ho colto male io il concetto e pensavo fosse un errore di battitura. Vedo che le regole le avete nominate da `Rule #0` a `Rule #4` , nessun numero `5` quindi. Probabilmente il valore corretto in questo caso sarebbe allora `slot definiti dalla Rule \#1 alla Rule \#4.` ?

2023-07-07 09:07 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/cookie.tex
> +	di tempo dopo il quale il cookie non deve essere inviato. E' molto utile per i cookie di sessione in quanto, se si pensa a una banca, è bene che se l'utente non termina manualmente la sessione, i co
Il concetto è che non deve essere inviato ma nella realtà il cookie dopo quella data viene eliminato automaticamente dal computer locale da come ho letto online. Meglio scrivere direttamente che il cookie viene eliminato automaticamente?

2023-07-07 09:08 UTC, CristianCosci commented
Anche io penso che non ci sia la necessità di utilizzare i vari vspace in quanto crea asimmetrie con il resto del pdf e anche in generale con l'approccio di tutti i vari appunti. Tendenzialmente li utilizzerei solo per la gestione particolare di alcune foto o di un distacco all'interno di testo dello stesso paragrafo/sezione per enfatizzarlo.

2023-07-07 09:12 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +In big endian, con short int, si ha:\\
Fatto

2023-07-07 09:13 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +``Fencin'' vuol dire \textbf{barriera}, cancello.
Fatto

2023-07-07 09:15 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo9_xss.tex
> +L'attacco viene detto "\textit{reflected}" perché il server web ha riflesso la domanda. Il sito è giusto,
Fatto

2023-07-07 09:16 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/cookie.tex
> +	\item \textbf{HttpOnly}: Impedisce a JavaScript di accedere al cookie, ad esempio tramite la proprietà Document.cookie. Si noti che un cookie che è stato creato con HttpOnly verrà comunque inviato c
Fatto

2023-07-07 09:31 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/cookie.tex
> +		\item \textbf{Strict}: Significa che il browser invia il cookie solo per le richieste same-site, ovvero richieste provenienti dallo stesso sito che ha impostato il cookie. Se una richiesta proviene
Da come ho capito i cookie non vengono proprio inviati. Di seguito ti faccio un esempio:

Stai su un sito e viene settato questo cookie: `Set-Cookie: promo_shown=1; SameSite=Strict`

Finchè l'utente sarà su questo sito, il cookie verrà inviato con la richiesta come previsto. Tuttavia, quando si segue una connessione a tale sito tramite un link presente in un altro dominio o tramite un'email ecc... , su tale richiesta iniziale il cookie non verrà inviato.

2023-07-07 09:34 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/xxe.tex
> +comprometterne i file locali (come ad esempio /etc/shadow che memorizza credenziali importanti).
Fatto

2023-07-07 09:35 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/xxe.tex
> +Come possiamo vedere, questo codice presenta più di un problema ma il più importante sicuramente è che potremmo chiamare noi stessi la funzione sendScreenshotToSupport() con le nostre immagini. Potre
Fatto

2023-07-07 09:38 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/xxe.tex
> +N.B. Per un hacker è facile capire se un'azienda usa XML o meno e la maggior parte delle volte lo usa. Questo perchè quando le aziende di software aziendale crescono, spesso aggiornano il loro softwa
Fatto. Va benissimo `nota`, li per li non mi era venuto in mente che negli appunti da quaderno uso quella sigla di solito.

2023-07-07 09:41 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/main.tex
> +\setemojifont{NotoColorEmoji.ttf}[Path=fonts/]
Quindi dici di fare questi passaggi?

1. Togliere il commento alla tua riga di codice
2. Commentare la mia riga di codice
3. Eliminare la cartella `fonts` dalla directory

2023-07-07 09:43 UTC, CristianCosci commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +\paragraph{Esempio.}\
Ne metterei comunque due per omologare il tutto, renderlo di più facile comprensione (in quanto abbiamo sempre fatto con due) ed evitare incompatibilità con altri editor e compilatori.

2023-07-07 09:51 UTC, ncvescera commented
> Tendenzialmente li utilizzerei solo per la gestione particolare di alcune foto o di un distacco all'interno di testo dello stesso paragrafo/sezione per enfatizzarlo.

A questo non avevo pensato. Direi può andare bene così 🚀 
@Meht-evaS Vediamo se arriveranno altri pareri, sennò puoi procedere come suggerisce @CristianCosci

2023-07-07 10:01 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +Alla fine la variabile \verb|x| conterrà il valore $100+256=356$. \\
Ho un dubbio però.
Negli appunti diciamo:

>Il thread 2 scrive 300, cioè $256+44$. Prima setta la parte bassa, cioè la parte meno significativa, a $44$; poi quella più significativa a $256$.
$300$ infatti non ci sta in 8 bit.

300 non ci sta in 8 bit e siamo d'accordo. Ma anche 256 non ci sta in 8 bit (0-255) 🤔 qundi il thread non potrebbe scrivere 256 nella "parte alta", ma al più 255.

Mi sta sfuggendo qualcosa ?

2023-07-07 10:04 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/cookie.tex
> +	di tempo dopo il quale il cookie non deve essere inviato. E' molto utile per i cookie di sessione in quanto, se si pensa a una banca, è bene che se l'utente non termina manualmente la sessione, i co
> Il concetto è che non deve essere inviato ma nella realtà il cookie dopo quella data viene eliminato automaticamente dal computer locale

Ok, così ha senso.
Penso che, per evitare ambiguità, potresti scrivere tutte e due. Magari lasci la frase com'è e tra parentesi ci metti che nella realtà il cookie viene eliminato quando scade e quindi effetivamente non lo puoi inviare perchè non esiste più.

2023-07-07 10:07 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +\paragraph{Esempio.}\
> Ne metterei comunque due

Ricontrollo se sulla nostra configurazione funziona.
Potrei essere io che ho sempre fatto così perchè ho visto che funzionava senza però cercare se fosse effettivamente il modo migliore 😂 (vedi le virgolette)

2023-07-07 10:10 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +Alla fine la variabile \verb|x| conterrà il valore $100+256=356$. \\
Si ti sta sfuggendo il concetto che stiamo usando una variabile di tipo `short int` che vale `2 byte`. Quindi dobbiamo prendere tutti i 16 bit per formare il numero da rappresentare. Difatti `256` risulta essere semplicemente `1 bit` nonchè il primo del secondo ottetto.

2023-07-07 10:13 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +\paragraph{Esempio.}\
Ho provato e funziona, ma deve esserci uno spazio tra il `paragraph` e il resto del testo.

Questo non funziona !
```latex
\paragraph{Titolo}\
Io sono del testo
```
 Così si.
```latex
\paragraph{Titolo}\

Io sono del testo
```

@CristianCosci per me può lasciare così com'è e penso sia anche più corretto. Usare `\ \\` vorrebbe dire andare ad aggiungere uno spazio dopo e poi andare a capo 🤔 penso faccia un po schfio

2023-07-07 10:18 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/main.tex
> +\setemojifont{NotoColorEmoji.ttf}[Path=fonts/]
Esatto.
A questo posso anche pensarci io prima di effettuare il merge quando siamo sicuri che non dobbiamo più apportare modifiche.

2023-07-07 10:19 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +\paragraph{Esempio.}\
> Ne metterei comunque due per omologare il tutto, renderlo di più facile comprensione (in quanto abbiamo sempre fatto con due) ed evitare incompatibilità con altri editor e compilatori.

Non vorrei sbagliare ma mi sa che nel file già ce ne era almeno uno che io l'ho visto usato per la prima volta qui . Poi potrei comunque sbagliarmi per quanto sto fuso per l'esame ahahah. Comunque essendo che funziona anche con la vostra configurazione ditemi voi come preferite. Alla peggio, se non vi piace, io semmai addirittura proporrei di togliere gli spazi e mettere tutto su una riga per il semplice fatto che poi sennò l'immagine sotto va a nuova pagina e causa un disastro (ecco anche perchè ho usato i vspace in questo contesto).
![image](https://github.com/Typing-Monkeys/AppuntiUniversita/assets/57435273/1bfe1b96-12a0-4b38-a50e-feeb55bd99bc)

2023-07-07 10:29 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/cookie.tex
> +	di tempo dopo il quale il cookie non deve essere inviato. E' molto utile per i cookie di sessione in quanto, se si pensa a una banca, è bene che se l'utente non termina manualmente la sessione, i co
Perfetto perfetto. Appena corretto come suggerito.

2023-07-07 12:35 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/ethereum/contract_security.tex
Fatto

2023-07-07 12:46 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/id_managing/oauth.tex
Fatto

2023-07-07 12:49 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo2_buff_over.tex
> +
Grazie mille!

2023-07-07 14:20 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/ethereum/introduzione.tex
Fatto

2023-07-07 14:47 UTC, Meht-evaS commented
Ho applicato tutte le correzioni consigliate. Ho solo lasciato un paio di \vspace{} attorno a una foto in `capitolo6_threads` e `capitolo9_xss` perchè a toglierli si sformattano troppe cose. Se pensate che è meglio togliere anche quelli fatemelo sapere.
@ncvescera @CristianCosci

2023-07-07 19:46 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo9_xss.tex
> +slot definiti dalla Rule \#0 alla Rule \#4.
Si, ora ricordo. Nelle slide che avevamo c'era scritto che esistevano queste 5 regole, ma ce n'earno solo 4 😂 
lo avevamo lasciato perchè ci dava ritardo 😂 

Va benissimo come l'hai corretto !

2023-07-07 20:13 UTC, ncvescera requested changes
I restanti `vspace` possiamo lascialri.
C'è un piccolo errore che ho trovato, ma per il resto ottimo 👍🏻

2023-07-07 20:13 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo9_xss.tex
>  \paragraph{Rule \#1:} : \textit{effettuare \textbf{escaping} del codice HTML
C'è un carattere di troppo

```suggestion
\paragraph{Rule \#1:} \textit{effettuare \textbf{escaping} del codice HTML
```

2023-07-07 20:17 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +\paragraph{Esempio.}\
Qui forse viene fuori casino perchè ho messo l'immagine all'interno del testo. Probabilmente è un caso limite che non ci era mai capitato e non ci siamo accorti del fatto che potesse succedere.

Va bene come hai fatto e che hai lasciato alcuni vspce 👍🏻

2023-07-07 20:21 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo6_threads.tex
> +Alla fine la variabile \verb|x| conterrà il valore $100+256=356$. \\
Risolto !

2023-07-07 20:22 UTC, ncvescera commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/web_security/cookie.tex
> +		\item \textbf{Strict}: Significa che il browser invia il cookie solo per le richieste same-site, ovvero richieste provenienti dallo stesso sito che ha impostato il cookie. Se una richiesta proviene
Certo, è chiaro. La spiegazione aggiunta nella parte precedente dovrebbe essere chiara e risolvere eventuali dubbi 🚀

2023-07-08 15:38 UTC, Meht-evaS commented on magistrale/Anno 1/Cybersecurity/latex/santini/capitoli/secure_coding/capitolo9_xss.tex
>  \paragraph{Rule \#1:} : \textit{effettuare \textbf{escaping} del codice HTML
Fatto

2023-07-25 21:09 UTC, F-a-b-r-i-z-i-o approved these changes

2023-07-25 21:19 UTC, ncvescera requested changes
Questa PR non è pronta per il Merge, va rimosso il file del font e ripristiano il font originale

2023-08-12 16:43 UTC, ncvescera approved these changes

2023-08-14 20:51 UTC, ncvescera commented
Prima di effetutare il merge di questa risolviamo la #59 così abbiamo la release funzionante.

2023-08-17 06:35 UTC, merged