feat(appunti): Advanced and Distributed Algorithms LaTex
Typing-Monkeys/AppuntiUniversita pull request #53
Opened 2023-08-08 13:44 UTC by ncvescera

Riscritti gli appunti del modulo 1 (Pinotti) dell'esame di Advanced and Distributed Algorithms in LaTex

2023-08-08 13:50 UTC, F-a-b-r-i-z-i-o approved these changes

2023-08-08 14:02 UTC, CristianCosci requested changes
Non dovremmo utilizzare lo stesso template degli altri appunti?

2023-08-08 14:02 UTC, ncvescera commented
> Ho notato solo ora che non viene utilizzato il template classico per il latex

Si, va corretto.
Prima di approvare tutto va ricontrollato e riletto tutto

2023-08-08 15:47 UTC, TommasoRomani commented
> Okok, pensavo fossero già stati riletti e controllati

Gli appunti dovrebbero essere corretti, l'unica cosa diversa dal template credo sia l'indice che per fare prima si era usato un convertitore automatico e lo ha fatto in quel modo

2023-08-08 16:43 UTC, ncvescera commented
> > Okok, pensavo fossero già stati riletti e controllati
> 
> Gli appunti dovrebbero essere corretti, l'unica cosa diversa dal template credo sia l'indice che per fare prima si era usato un convertitore automatico e lo ha fatto in quel modo

È diverso l'indice e la prima pagina. Il template usato è quello "per le relazioni" dove ci sono i nomi degli studenti e dei docenti.
Facciamo subito a cambiarlo, non è un problema

2023-08-14 10:13 UTC, CristianCosci approved these changes

2023-08-14 10:16 UTC, CristianCosci requested changes
Ricaricare pdf con quote aggiornata

2023-08-14 11:05 UTC, ncvescera reviewed
Meravigliosa ❤️ 
Appena posso aggiorno il pdf 🚀

2023-08-16 14:06 UTC, CristianCosci approved these changes

2023-08-16 18:55 UTC, F-a-b-r-i-z-i-o approved these changes

2023-09-18 14:47 UTC, F-a-b-r-i-z-i-o approved these changes

2023-09-19 10:26 UTC, TommasoRomani approved these changes

2023-10-07 08:30 UTC, CristianCosci approved these changes

2023-10-07 10:02 UTC, merged