Appunti di calcolo numerico
Typing-Monkeys/AppuntiUniversita pull request #55
Opened 2023-08-11 10:58 UTC by michelevantaggi02

Questi sono i miei appunti di calcolo numerico, al momento la cartella contiene:

- Dispense fornite dal professor Iannazzo (condivide un file zip con questi file)
- File markdown divisi per argomenti
- File completo (è un semplice merge dei file inclusi nella cartella argomenti)
- Export in pdf del file completo

2023-08-11 17:13 UTC, ncvescera commented
@CristianCosci delle dispense di Bruno che ne facciamo ? Non penso serva includerle nella cartella finale.
Per ora le lasciamo e poi prima del merge le eliminiamo ?

2023-08-13 12:02 UTC, ncvescera requested changes
Ottimo 👍🏻 
Ho riletto tutti gli appunti ed in generale devo dire molto bene. Sono un po' succinti e sintetici ma vanno bene (tendiamo a prediligere appunti un po' più discorsivi che cercano di spiegarti bene ogni cosa, a prova di imbecille diciamo).

Ho trovato alcune imprecisioni e piccoli typo che ho segnalato e vanno corretti.
C'è anche da sistemare tutte le volte che compare l'insieme dei numeri reali $\mathbb{R}$ ma è scritto $R$. Sarebbe meglio distinguere quando è effettivamente l'insieme dei numeri reali da qualche altra cosa.

Ti consiglio poi di non superare gli 80 caratteri a riga. Quando scrivi un documento e "metti tutto su una riga" risulta abbastanza difficile controllare il codice per chi lo leggerà. Non serve che lo correggi in questa PR ma è un consiglio per il futuro 🚀 

Ho anche qualche dubbio su com'è organizzato il documento. L'ordine in cui compaiono i vari capitoli è voluto ed è l'ordine giusto o vanno riorganizzati ?
Che differenza c'è tra i titoletti in giallo, rosso, rosso che iniziano con numero/lettera ?

Hai anche degli esercizi pratici svolti ? Ricordo che Bruno dava la possibilità di svolgere un esame compilativo in cui era necessario solo saper fare gli esercizi a "cervello spento".
Sarebbe interessante avere anche degli esercizi già svolti

2023-08-13 12:02 UTC, ncvescera requested changes
Ottimo 👍🏻 
Ho riletto tutti gli appunti ed in generale devo dire molto bene. Sono un po' succinti e sintetici ma vanno bene (tendiamo a prediligere appunti un po' più discorsivi che cercano di spiegarti bene ogni cosa, a prova di imbecille diciamo).

Ho trovato alcune imprecisioni e piccoli typo che ho segnalato e vanno corretti.
C'è anche da sistemare tutte le volte che compare l'insieme dei numeri reali $\mathbb{R}$ ma è scritto $R$. Sarebbe meglio distinguere quando è effettivamente l'insieme dei numeri reali da qualche altra cosa.

Ti consiglio poi di non superare gli 80 caratteri a riga. Quando scrivi un documento e "metti tutto su una riga" risulta abbastanza difficile controllare il codice per chi lo leggerà. Non serve che lo correggi in questa PR ma è un consiglio per il futuro 🚀 

Ho anche qualche dubbio su com'è organizzato il documento. L'ordine in cui compaiono i vari capitoli è voluto ed è l'ordine giusto o vanno riorganizzati ?
Che differenza c'è tra i titoletti in giallo, rosso, rosso che iniziano con numero/lettera ?

Hai anche degli esercizi pratici svolti ? Ricordo che Bruno dava la possibilità di svolgere un esame compilativo in cui era necessario solo saper fare gli esercizi a "cervello spento".
Sarebbe interessante avere anche degli esercizi già svolti

2023-08-13 19:41 UTC, michelevantaggi02 commented
> Ho anche qualche dubbio su com'è organizzato il documento. L'ordine in cui compaiono i vari capitoli è voluto ed è l'ordine giusto o vanno riorganizzati ?

L'ordine è quello con cui ha spiegato i vari argomenti, letteralmente in ordine cronologico, i nomi dei file sono in ordine alfabetico perché obsidian li ordina in quel modo e se non metto un qualche prefisso poi per fare il merge mi sposta tutto 

> Che differenza c'è tra i titoletti in giallo, rosso, rosso che iniziano con numero/lettera ?

Sono i vari titoletti con gli # (quindi i vari h1, h2, ecc) , il tema che uso al posto di cambiare eccessivamente le dimensioni dei titoli li fa di colori diversi, se serve posso fare un PDF con il tema base (font Arial e titoli "normali")

> 
> Hai anche degli esercizi pratici svolti ?

Gli esercizi che ho fatto per la maggior parte sono sulle dispense del prof

> Ricordo che Bruno dava la possibilità di svolgere un esame compilativo in cui era necessario solo saper fare gli esercizi a "cervello spento".

Adesso ha cambiato un po', é diviso in 2 parti l'esame, la prima obbligatoria con 3 domande teoriche e 4(?) Esercizi, se prendi almeno 21 (il voto massimo è 22) sei ammesso alla seconda parte un po' più difficile e puoi arrivare a 30

2023-08-13 20:33 UTC, ncvescera commented
> L'ordine è quello con cui ha spiegato i vari argomenti, letteralmente in ordine cronologico, i nomi dei file sono in ordine alfabetico perché obsidian li ordina in quel modo e se non metto un qualche prefisso poi per fare il merge mi sposta tutto

Perfetto, grazie mille per il chiarimento 👍🏻 



> Sono i vari titoletti con gli # (quindi i vari h1, h2, ecc) , il tema che uso al posto di cambiare eccessivamente le dimensioni dei titoli li fa di colori diversi, se serve posso fare un PDF con il tema base (font Arial e titoli "normali")

No tranquillo, non serve che cambi tema, tanto il tutto verrà trasformato in LaTex (prima o poi). Era solo per capire quali fossero gli H1, H2, ecc.
Quindi quelli in rosso sono gli H1 e quelli in giallo H2 ?



> Adesso ha cambiato un po', é diviso in 2 parti l'esame, la prima obbligatoria con 3 domande teoriche e 4(?) Esercizi, se prendi almeno 21 (il voto massimo è 22) sei ammesso alla seconda parte un po' più difficile e puoi arrivare a 30

Ok perfetto 👍🏻 
Quindi nelle dispense ci sono esercizi già svolti ? Purtroppo quelle non le ho guardate ma rimedio appena posso.
Hai qualche domanda che ha fatto durante gli esami ?

2023-08-14 13:04 UTC, michelevantaggi02 commented
> Quindi quelli in rosso sono gli H1 e quelli in giallo H2 ?

> Quindi nelle dispense ci sono esercizi già svolti ? 

Si qualcosina c'è 

> Hai qualche domanda che ha fatto durante gli esami ?

Una volta mi sono portato a casa la traccia completa perché non avevo consegnato, ma mi sa che ho buttato tutto, appena ho tempo ricontrollo

2023-08-14 20:38 UTC, ncvescera commented
> Si qualcosina c'è

Perfetto, grazie mille 👍🏻 

> Una volta mi sono portato a casa la traccia completa perché non avevo consegnato, ma mi sa che ho buttato tutto, appena ho tempo ricontrollo

Apposto, se trovi qualcosa caricalo pure 🚀

2023-08-16 15:02 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/2. Error Analysis.md
> +$$F(\beta, t, m, M) = \{0\} \cup \{\pm \beta^p\sum_{i=1}^t {\beta^{-i}d_i}, \; -m \leq p \leq M, \; 0 \leq d_i < \beta \text{ intero per } i=1,...,t, \; d_1 \neq 0\}$$
Si dovrebbe essere scritto meglio, è l'insieme dei numeri in virgola mobile

2023-08-16 15:06 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/3. Errore Per Le Funzioni Razionali.md
> +^f13037
Non so se funziona in markdown base, identifica in modo univoco il blocco di codice che parte dalla riga 48 e può essere usato all'interno di un link per poter portare direttamente al blocco

2023-08-16 15:10 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a0. Sistemi lineari.md
> +v sottospazio vettoriale di dimensione l $o \leq l \leq n$
Credo proprio di si

2023-08-16 15:11 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a0. Sistemi lineari.md
> +la soluzione è unica $\iff rk(A)=rk(A|b)=n \iff n-rk(A)=0$
Si tendo a ricopiare un po' cosi come viene

2023-08-16 15:12 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a1. Algoritmo di Gauss.md
> +Non ce se la fa a staglie dietro mannaggia
Prima e ultima volta che ho provato a prendere appunti direttamente al pc ahahaha

2023-08-16 16:10 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/a0. Sistemi lineari.md
> +la soluzione è unica $\iff rk(A)=rk(A|b)=n \iff n-rk(A)=0$
No problemo, ci sta.
Appena puoi sistemalo 🚀

2023-08-16 16:10 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/a1. Algoritmo di Gauss.md
> +Non ce se la fa a staglie dietro mannaggia
AHHAHA eh si, Bruno è velocissimo quando spiega 🏃🏻

2023-08-17 10:32 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a3a. Esercizio.md
> +$8n
Sinceramente non ne ho idea

2023-08-17 10:34 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a5. Curva di Bezier.md
> +## 1
Pensavo di fare più esempi  ma ho scritto solo quello, penso si può rimuovere

2023-08-17 10:35 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a5. Curva di Bezier.md
> +(1-t)P_0 + tP_1$$
è scritta un po' a caso questa, se riesco la riscrivo meglio

2023-08-17 10:39 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a7. Interpolazione.md
> +$$det(V) = \prod_{\substack{i>j\\i,j=0}}^2{(x_i - x_j)} = (x_1 - x_0)(x_2 - x_1) (x_2 - x_0)$$
Ognuno implica il successivo, nel senso che significano praticamente la stessa cosa

2023-08-17 10:54 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a3a. Esercizio.md
> +$8n
Non mi ricordo cosa ho scritto, nel dubbio direi di toglierla

2023-08-17 10:58 UTC, michelevantaggi02 commented
> Apposto, se trovi qualcosa caricalo pure 🚀

@ncvescera ho trovato la traccia ma il foglio è tutto acciaccato, se non è un problema faccio una scansione e lo carico sennò per il momento non ho tempo di riscriverlo

2023-08-17 13:05 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/3. Errore Per Le Funzioni Razionali.md
> +^f13037
Non ne ho idea. È la prima volta che lo sento.
Non mi pare venga renderizzato nel pdf, quindi in caso lascialo.

2023-08-17 13:06 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/a5. Curva di Bezier.md
> +(1-t)P_0 + tP_1$$
Perfetto 👍🏻

2023-08-17 13:06 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/a5. Curva di Bezier.md
> +## 1
Toglilo pure

2023-08-17 13:07 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/a3a. Esercizio.md
> +$8n
Si toglilo pure

2023-08-17 13:15 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/a7. Interpolazione.md
> +$$det(V) = \prod_{\substack{i>j\\i,j=0}}^2{(x_i - x_j)} = (x_1 - x_0)(x_2 - x_1) (x_2 - x_0)$$
Ok, perfetto.
Se si equivalgono e ognuno implica il successivo direi di riscriverla meglio, del tipo come ho fatto io

2023-08-17 13:15 UTC, ncvescera commented
> > Apposto, se trovi qualcosa caricalo pure 🚀
> 
> @ncvescera ho trovato la traccia ma il foglio è tutto acciaccato, se non è un problema faccio una scansione e lo carico sennò per il momento non ho tempo di riscriverlo

Caricalo pure fin quando è leggibile ci va bene 🌈

2023-08-17 13:20 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/a0. Sistemi lineari.md
> +v sottospazio vettoriale di dimensione l $o \leq l \leq n$
Allora cambialo in 0

2023-08-17 13:24 UTC, ncvescera commented
@michelevantaggi02 Ho visto che hai richiesto la Review, non ne faccio una nuova perchè hai ancora alcune cose da risolvere e modificare.
Ho guardato le modifiche che hai apportato fino ad ora e vanno bene 👍🏻 Ricordati ti rigenerare il PDF quando hai finito 🚀

2023-08-17 14:36 UTC, michelevantaggi02 commented
> @michelevantaggi02 Ho visto che hai richiesto la Review, non ne faccio una nuova perchè hai ancora alcune cose da risolvere e modificare.

Sisi era giusto per segnalare che ho fatto tutte le modifiche che avevi segnato

> Ho guardato le modifiche che hai apportato fino ad ora e vanno bene 👍🏻 Ricordati ti rigenerare il PDF quando hai finito 🚀 

Si appena posso rifaccio il merge e il pdf

2023-08-17 14:38 UTC, ncvescera commented
> > @michelevantaggi02 Ho visto che hai richiesto la Review, non ne faccio una nuova perchè hai ancora alcune cose da risolvere e modificare.
> 
> Sisi era giusto per segnalare che ho fatto tutte le modifiche che avevi segnato
> 
> > Ho guardato le modifiche che hai apportato fino ad ora e vanno bene 👍🏻 Ricordati ti rigenerare il PDF quando hai finito 🚀
> 
> Si appena posso rifaccio il merge e il pdf

Perfetto 🚀

2023-08-20 09:34 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/3. Errore Per Le Funzioni Razionali.md
> +^f13037
Sisi nei pdf non c'è

2023-08-20 09:37 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a7. Interpolazione.md
> +$$det(V) = \prod_{\substack{i>j\\i,j=0}}^2{(x_i - x_j)} = (x_1 - x_0)(x_2 - x_1) (x_2 - x_0)$$
yes

2023-08-20 09:42 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a5. Curva di Bezier.md
@ncvescera questa era la formula che non si capiva, è l'esempio di calcolo di una curva di bezier con 2 punti soltanto, per farla capire meglio ho fatto più formule una sotto l'altra

2023-08-20 09:52 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/2. Error Analysis.md
> +$$\text {con} \; 0 \leq d_i < \beta \text{ intero per } i=1,...,t, \; d_1 \neq 0$$
@ncvescera ho spostato le condizioni su un'altra riga così dovrebbe essere più  facile da capire

2023-08-20 10:02 UTC, michelevantaggi02 commented
Il pdf ora non ha più i titoli colorati, a quanto pare il tizio che fa il tema che uso ha deciso di aggiornarlo così

2023-08-21 22:47 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/a7. Interpolazione.md
👍🏻

2023-08-21 22:51 UTC, ncvescera commented
> Il pdf ora non ha più i titoli colorati, a quanto pare il tizio che fa il tema che uso ha deciso di aggiornarlo così

Non è un problema, tanto poi verranno tradotti in LaTex 🌈 
Anzi, forse anche meglio così

2023-08-21 23:07 UTC, ncvescera commented
@michelevantaggi02 Ho guardato velocemente le modifiche che hai fatto e mi sembra tutto giusto. Appena posso ricontrollo tutto meglio.

Comunque ottimo lavoro 🚀

2023-09-25 08:22 UTC, ncvescera requested changes
Sono finalmente riuscito a controllare le modifiche e leggere il PDF completo.
Ho trovato alcune imprecisioni e problemi che andrebbero risolti. Dopo questi fix dovremmo esserci per il merge 🚀 

- Ricontrolla gli appunti e scrivi meglio gli insiemi come $\mathbb{R}$. Molto spesso l'insieme dei numeri reali $\mathbb{R}$ è scritto come $R$ e questo potrebbe essere confuso con un semplice insieme, magari definito qualche capitolo prima. Riguarda tutto il documento e specifica con `\mathbb{}` gli insiemi come quelli dei numeri realie o naturali. Te ne ho indicati alcuni, ma non sono tutti.
- Ho notato che una dimostrazione ha l'attributo `collapse:True` e nel PDF non viene mostrata (anche se nel file Markdown il codice c'è). Riguarda tutto il documento e assicurati che tutte le definizioni, dimostrazioni, ecc. siano correttamente mostrate.

2023-09-25 08:22 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/CalcNum-merged.md
> +$$D_n = \{A \in K^{nxn},, a_{ij} = 0, i \neq j\}$$
Ci sono 2 virgole, manca qualcosa o è solo un typo ?

2023-09-25 08:22 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/CalcNum-merged.md
> +Il sistema lineare $Ax = b$ ammette soluzione se e solo se rango(A) = rango(A|b).
```suggestion
Il sistema lineare $Ax = b$ ammette soluzione se e solo se $rango(A) = rango(A|b)$.
```

2023-09-25 08:22 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/CalcNum-merged.md
> +Se esiste almeno una soluzione allora l'insieme delle soluzioni è un sottospazio affine di dimensione n-rango(A).
```suggestion
Se esiste almeno una soluzione allora l'insieme delle soluzioni è un sottospazio affine di dimensione $n-rango(A)$.
```

2023-09-25 08:22 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/CalcNum-merged.md
> +$Ax=b \iff c_1x_1+c_2x_2+...+c_nx_n=b \iff$ $b$ è combinazione lineare delle colonne di $A$ $\iff$ rango(A)=rango(A|b)
```suggestion
$Ax=b \iff c_1x_1+c_2x_2+...+c_nx_n=b \iff$ $b$ è combinazione lineare delle colonne di $A$ $\iff rango(A)=rango(A|b)$
```

2023-09-25 08:22 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/CalcNum-merged.md
> +\end{bmatrix}
L'elemento dopo l'uguale è corretto vuoto oppure hai dimenticato qualcosa ?

2023-09-25 08:22 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/CalcNum-merged.md
> +$$ p(x_j) = \sum_{i=0}^n {y_i L_i(x_j)} = y_jL_j(x_j) = y_j$$
Tutta questa dimostrazione nel pdf non viene mostrata !

2023-10-06 12:16 UTC, F-a-b-r-i-z-i-o approved these changes

2023-10-07 10:14 UTC, ncvescera commented
@michelevantaggi02 ottime le modifiche e correzioni, te ne mancano ancora alcune da risolvere e alla fine riaggiorna il PDF 🦧

2023-10-23 08:20 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/CalcNum-merged.md
> +$$D_n = \{A \in K^{nxn},, a_{ij} = 0, i \neq j\}$$
typo

2023-10-23 09:59 UTC, ncvescera requested changes
Molto bene l'aggiunta della matrice tridiagonale per visualizzarla subito 👍🏻 
Ho trovato due piccoli errori che sono stati aggiunti nei commit recenti.
Appena li risolvi, aggiorna il file merged ed il pdf e ci siamo 🚀

2023-10-23 09:59 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/a0. Sistemi lineari.md
> +Il sistema lineare $Ax = b$ ammette soluzione se e solo se rango$rango(A) = rango(A|b)$.
Hai ripetuto due volte la parola 'rango'

```suggestion
Il sistema lineare $Ax = b$ ammette soluzione se e solo se $rango(A) = rango(A|b)$.
```

2023-10-23 09:59 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/argomenti/a0. Sistemi lineari.md
> +Se esiste almeno una soluzione allora l'insieme delle soluzioni è un sottospazio affine di dimensione n-rango(A).
Avevamo detto di togliere la formula matematica o l'hai rimossa per sbaglio ?

```suggestion
Se esiste almeno una soluzione allora l'insieme delle soluzioni è un sottospazio affine di dimensione $n-rango(A)$.
```

2023-10-24 09:02 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/argomenti/a0. Sistemi lineari.md
> +Se esiste almeno una soluzione allora l'insieme delle soluzioni è un sottospazio affine di dimensione n-rango(A).
tolta per sbaglio

2023-10-24 10:04 UTC, ncvescera commented on triennale/Anno 2/Calcolo Numerico/CalcNum-merged.md
> +$$\mathbb{R}32 \iff \{d_i\}_{i=1,2,3....}, \quad d_i \in \{0,...,\beta -1\}$$
Perchè qui è comparso un 32 ?

2023-10-24 10:11 UTC, CristianCosci commented
@ncvescera Rimuoverei le dispense di bruno dalla cartella in quanto vi è espressamente scritto che non gradisce la ripubblicazione su internet. Eventualmente lascerei solo un link che riporta alla pagina dove poterle scaricare

2023-10-24 10:13 UTC, michelevantaggi02 commented on triennale/Anno 2/Calcolo Numerico/CalcNum-merged.md
> +$$\mathbb{R}32 \iff \{d_i\}_{i=1,2,3....}, \quad d_i \in \{0,...,\beta -1\}$$
typo🤦🏻

2023-10-24 19:14 UTC, ncvescera approved these changes

2023-10-24 19:43 UTC, CristianCosci approved these changes

2023-10-25 11:56 UTC, F-a-b-r-i-z-i-o approved these changes

2023-10-25 13:17 UTC, merged