Aggiunti Appunti Linguaggi
Typing-Monkeys/AppuntiUniversita pull request #67
Opened 2023-10-07 21:48 UTC by Gaiasem

2023-10-08 09:11 UTC, CristianCosci commented
@ncvescera Qui aggiungerei anche il PDF che dava Carpi dei suoi appunti

2023-10-08 09:19 UTC, ncvescera commented
> @ncvescera Qui aggiungerei anche il PDF che dava Carpi dei suoi appunti

Dobbiamo trovarlo ma ci sta.
C'è ancora su Unistudium ?

2023-10-08 10:04 UTC, CristianCosci commented
> > @ncvescera Qui aggiungerei anche il PDF che dava Carpi dei suoi appunti
> 
> Dobbiamo trovarlo ma ci sta. C'è ancora su Unistudium ?

si penso di si

2023-10-08 17:25 UTC, CristianCosci submitted a review, later dismissed

2023-10-08 21:06 UTC, F-a-b-r-i-z-i-o submitted a review, later dismissed

2023-10-09 13:57 UTC, ncvescera requested changes
Direi di creare una cartella `dispense` e mettere al suo interno le varie dispense, così da separare gli appunti dalle dispense.

2023-10-09 16:47 UTC, CristianCosci approved these changes

2023-10-10 08:34 UTC, ncvescera approved these changes

2023-10-10 08:55 UTC, F-a-b-r-i-z-i-o approved these changes

2023-10-10 16:23 UTC, merged