Aggiunti appunti comandi SQL
Typing-Monkeys/AppuntiUniversita pull request #72
Opened 2023-10-30 19:05 UTC by Meht-evaS

File che contiene tutti i principali comandi SQL e la definizione dei vari tipi di variabili, chiavi, ecc...

2023-12-17 16:59 UTC, ncvescera requested changes
Grazie mille per questi appunti 🚀
Ho trovato alcune imprecisioni che ho segnalato.

2023-12-17 16:59 UTC, ncvescera commented on triennale/Anno 3/Basi di Dati/ComandiSQL.md
> +			Serve per la definizione di chaivi esterne su più attributi
```suggestion
			Serve per la definizione di chiavi esterne su più attributi
```

2023-12-17 16:59 UTC, ncvescera commented on triennale/Anno 3/Basi di Dati/ComandiSQL.md
> +			Serve per la definizione di chaivi esterne su più attributi
```suggestion
			Serve per la definizione di chiavi esterne su più attributi
```

2023-12-17 16:59 UTC, ncvescera commented on triennale/Anno 3/Basi di Dati/ComandiSQL.md
> +-- AS serve a dare uno psudonimo alla tabella in uso
```suggestion
-- AS serve a dare uno pseudonimo alla tabella in uso
```

2023-12-17 16:59 UTC, ncvescera commented on triennale/Anno 3/Basi di Dati/ComandiSQL.md
> +Date due tabelle che hanno almeno una colonna in comune (cioè con lo stesso nome), si avrà in output una tabella che contiene tutte le tuple in cui si hanno dei valori in cumune nella colonna in comu
```suggestion
Date due tabelle che hanno almeno una colonna in comune (cioè con lo stesso nome), si avrà in output una tabella che contiene tutte le tuple in cui si hanno dei valori in comune nella colonna in comune fra le due tabelle. L'attributo in comune delle due relazioni è presente una sola volta nella tabella join in uscita.
```

2023-12-17 16:59 UTC, ncvescera commented on triennale/Anno 3/Basi di Dati/PrimeEsercitazioniCommentate.md
> +  	<summary><b>Clicca per vedere la soluzione sottoforma di SCRIPT!</b></summary>
```suggestion
  	<summary><b>Clicca per vedere la soluzione sotto forma di SCRIPT!</b></summary>
```

2023-12-17 16:59 UTC, ncvescera commented on triennale/Anno 3/Basi di Dati/PrimeEsercitazioniCommentate.md
> +	- l'anno di produzione del primo film interpretato da ogni attore elencaro nel risultato della query
```suggestion
	- l'anno di produzione del primo film interpretato da ogni attore elencarlo nel risultato della query
```

2023-12-17 16:59 UTC, ncvescera commented on triennale/Anno 3/Basi di Dati/PrimeEsercitazioniCommentate.md
> +-- Ottenere i titoli dei libri e la sala in cui sono collocati, includendo le opere di cui non e' possibile repereire la collocazione
```suggestion
-- Ottenere i titoli dei libri e la sala in cui sono collocati, includendo le opere di cui non e' possibile reperire la collocazione
```

2023-12-17 17:52 UTC, Meht-evaS commented on triennale/Anno 3/Basi di Dati/PrimeEsercitazioniCommentate.md
> +	- l'anno di produzione del primo film interpretato da ogni attore elencaro nel risultato della query
Penso che qua sia più un elencato, sbaglio?

2023-12-18 09:55 UTC, ncvescera commented on triennale/Anno 3/Basi di Dati/PrimeEsercitazioniCommentate.md
> +	- l'anno di produzione del primo film interpretato da ogni attore elencaro nel risultato della query
Si, giustissimo. L'ho corretto

2023-12-18 21:43 UTC, Meht-evaS commented on triennale/Anno 3/Basi di Dati/ComandiSQL.md
> +			Serve per la definizione di chaivi esterne su più attributi
Fatto

2023-12-18 21:44 UTC, Meht-evaS commented on triennale/Anno 3/Basi di Dati/ComandiSQL.md
> +			Serve per la definizione di chaivi esterne su più attributi
Fatto

2023-12-18 21:44 UTC, Meht-evaS commented on triennale/Anno 3/Basi di Dati/ComandiSQL.md
> +-- AS serve a dare uno psudonimo alla tabella in uso
Fatto

2023-12-18 21:45 UTC, Meht-evaS commented on triennale/Anno 3/Basi di Dati/ComandiSQL.md
> +Date due tabelle che hanno almeno una colonna in comune (cioè con lo stesso nome), si avrà in output una tabella che contiene tutte le tuple in cui si hanno dei valori in cumune nella colonna in comu
Fatto

2023-12-18 21:45 UTC, Meht-evaS commented on triennale/Anno 3/Basi di Dati/PrimeEsercitazioniCommentate.md
> +  	<summary><b>Clicca per vedere la soluzione sottoforma di SCRIPT!</b></summary>
Fatto

2023-12-18 21:47 UTC, Meht-evaS commented on triennale/Anno 3/Basi di Dati/PrimeEsercitazioniCommentate.md
> +-- Ottenere i titoli dei libri e la sala in cui sono collocati, includendo le opere di cui non e' possibile repereire la collocazione
Fatto

2023-12-20 09:09 UTC, ncvescera approved these changes

2023-12-20 10:01 UTC, F-a-b-r-i-z-i-o approved these changes

2024-04-18 08:42 UTC, merged