Aggiunta esempio modalità esame fax simile Santini
Typing-Monkeys/AppuntiUniversita pull request #77
Opened 2023-12-15 11:32 UTC by Meht-evaS

Ho riscritto anche il file README iniziale così che rimanda alla tipologia d'esame corretta che si vuole visualizzare.

2023-12-17 16:09 UTC, ncvescera requested changes

2023-12-17 16:09 UTC, ncvescera commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/c_sources/esercizio 4/write.c
> +		- PRIMA DELLA CORREZZIONE: count a riga 3 è definita e ha linkage interno
```suggestion
		- PRIMA DELLA CORREZIONE: count a riga 3 è definita e ha linkage interno
```

2023-12-17 16:09 UTC, ncvescera commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/c_sources/esercizio 4/write.c
> +		- DOPO LA CORREZZIONE: count a riga 3 è definita e ha linkage esterno
```suggestion
		- DOPO LA CORREZIONE: count a riga 3 è definita e ha linkage esterno
```

2023-12-17 16:13 UTC, ncvescera commented
@Meht-evaS ottimo lavoro. Molto bene il README che specifica i fire file e le modalità d'esame.
Ho trovato alcuni typo da correggere e alcuni dubbi che ho segnalato

2023-12-17 17:32 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/README.md
> +	* Sritto in Latex sfruttando il package [exam](https://ctan.org/pkg/exam?lang=en).
Fatto

2023-12-17 17:33 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/README.md
> +Eaborato con gli esercizi, e relative soluzioni, per l'esame di Programmazione Procedurale con Laboratorio.
Fatto

2023-12-17 17:34 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/README.md
> +362384
Si si hai più che ragione. Non ho pensato a toglierle quando ho fatto il copia e incolla dei file dal mio repository d'esame a questo. Comunque li ho tolti.

2023-12-17 17:35 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/README.md
> +* Sritto in Latex sfruttando il package [exam](https://ctan.org/pkg/exam?lang=en).
Fatto

2023-12-17 17:35 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/README.md
> +* [Compito d'esame con correzioni](pdf/didattica_inf_esame_prog1_con_soluzioni_cerami.pdf): identico al precedente file ma al suo interno contiene la risposte (correzioni) degli esercizi. Anche qui v
Fatto

2023-12-17 17:38 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/c_sources/esercizio 1/Es_1.c
> +	printf("a: %d\n", a); //4
Si me ne sono accorto solo ora. Mi ha sminchiato tutte le tabulazioni fatti su SublimeText se ti riferisci al codice in generale. Se ti riferisci invece a quelle del ragionamento del contenuto dei valori all'interno dei cicli allora è una mia cosa volontaria. Le tabulazioni servono a mostrare nelle stesse colonne gli stessi punti di ragionamento ad ogni ciclo. Se pensi sia sbagliato posso mettere tutto in un'unica colonna.

2023-12-17 17:46 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/c_sources/esercizio 2/Es_2.c
> +	linea 9: il valore dopo l'uguale è converito da int (dopo la conversione esplicita) a unsigned char
Fatto

2023-12-17 17:47 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/c_sources/esercizio 4/write.c
> +		- PRIMA DELLA CORREZZIONE: count a riga 3 è definita e ha linkage interno
Mamma mia che orrore che ho messo ahahah. Corretto

2023-12-17 17:47 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/c_sources/esercizio 4/write.c
> +		- DOPO LA CORREZZIONE: count a riga 3 è definita e ha linkage esterno
Orrore corretto pt2

2023-12-18 09:54 UTC, ncvescera commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/c_sources/esercizio 1/Es_1.c
> +	printf("a: %d\n", a); //4
Intendevo l'indentazione generale del codice e non quella dei commenti (va molto bene).
Ok perfetto, è stato solo un problema di indentazione e nulla di volontario 🚀 
Magari appena puoi sistema l'indentazione e poi ci siamo

2023-12-18 21:36 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/c_sources/esercizio 1/Es_1.c
> +	printf("a: %d\n", a); //4
Fatto

2023-12-18 21:56 UTC, Meht-evaS commented on magistrale/Anno 1/Didattica/Santini/FaxSimileEsame/c_sources/esercizio 1/Es_1.c
> +	printf("a: %d\n", a); //4
Corrette tutte le tabulazioni per ogni esercizio

2023-12-20 09:06 UTC, ncvescera approved these changes

2023-12-20 10:01 UTC, F-a-b-r-i-z-i-o approved these changes

2024-04-18 08:13 UTC, merged