Computational Intelligence
Typing-Monkeys/AppuntiUniversita pull request #9
Opened 2022-07-15 09:05 UTC by CristianCosci

2022-07-15 10:16 UTC, ncvescera commented
Perfetto come al solito 🚀 
Sono appunti e materiali completi o devi ancora aggiungere qualcosa ?

Appena posso controllo tutto 🦧

2022-07-16 15:37 UTC, CristianCosci commented
Sono completi, codice degli algoritmi visti e appunti delle lezioni

2022-07-18 07:07 UTC, ncvescera commented
Ottimo 👍🏻

2022-07-18 07:09 UTC, ncvescera requested changes
Ho guardato in modo molto veloce tutti i file e prima di tutto elimina, dalle cartelle degli algoritmi, le cartelle `__pychache__`.

Ho iniziato a leggere gli appunti, ho trovato una piccola modifica da effettuare. Continuero' a leggerli in modo accurato il prima possibile.

Grazie ancora per l'aiuto !

2022-07-18 16:40 UTC, ncvescera requested changes
Suggerite alcune modifiche ed elementi da correggere.

Continueremo la revisione quando inizieremo a studiare dagli appunti. La PR rimarrà ancora aperta. 

Per quello che ho letto è un ottimo lavoro !

2022-08-24 07:28 UTC, ncvescera commented
Scusa per l'assenza, appena posso controllo tutto !
Stiamo studiando per Cybersecurity e ci sta portando via molto tempo 😞

2022-08-24 09:55 UTC, CristianCosci commented
Assolutamente nessun problema, capisco le difficoltà (soprattutto per la parte di bistarelli). A che punto siete? Vi potrebbe servire una mano? Io in questi giorni sono un pò impegnato ma a settembre (Se voi avete finito la parte di sicurezza) potrei mettermi giù a fare la combo navarra-pinotti.

2022-08-24 10:05 UTC, ncvescera commented
Abbiamo finito la parte di Santini e stiamo combattendo con Bistarelli (lo abbiamo appena iniziato) 🙃.
Tu lo hai già dato e in caso da dove hai studiato ?

Ti lascio il link all'issue che abbiamo per cybersecurity ( #11 ).

Se riuscissi a fare la combo Navarra-Pinotti non sarebbe per niente male 💋 !!

2022-08-24 10:07 UTC, CristianCosci commented
No purtroppo di sicurezza non ho seguito quasi niente tranne le prime lezioni e devo ancora darlo 🙃.
Perfetto, poi do un'occhiata allora

2022-08-24 10:40 UTC, ncvescera commented
Seguire le lezioni non so quanto possa essere utile (come quasi per tutte le altre materie) 😉 
Le slide e il materiale caricato è abbastanza osceno.

Per santini abbiamo letto dai vari libri che ci consigliava che sono fatti bene.
Per bistarelli stiamo leggendo dal libro e sistemando gli appunti che ci ha dato @F-a-b-r-i-z-i-o .

2022-10-04 07:51 UTC, closed without merging